### PR TITLE
fix: race condition on blsagg

### PR DESCRIPTION
**Pull request by chzyer**
Fixes # .

### What Changed?
Fixed the race condition when accessing the `signedTaskRespsCs` map.

### Reviewer Checklist
- [ ] Code is well-documented
- [ ] Code adheres to Go [naming conventions](https://go.dev/doc/effective_go#names)
- [ ] Code deprecates any old functionality before removing it

### CODE REVIEW

**Comment by samlaf** [comment]
Hey! Thanks for this :)
I was super excited when I first saw this because I thought this was fixing #79 , but seems like its not heh. Still have to investigate that one to figure out where the race is coming from. 

Anyhow thanks for fixing this one. Would you mind changing the code to
```
a.taskChansMutex.Lock()
defer a.taskChansMutex.Unlock()
if _, taskExists := a.signedTaskRespsCs[taskIndex]; taskExists {
return TaskAlreadyInitializedErrorFn(taskIndex)
}
signedTaskRespsC := make(chan types.SignedTaskResponseDigest)
a.signedTaskRespsCs[taskIndex] = signedTaskRespsC
```
Personally find the defer easier to understand than your split if/else with an unlock in between.

**Comment by chzyer** [comment]
Thanks @samlaf! That makes sense to me. I’ve already sent a new commit.

**Comment by chzyer** [comment]
Hey @samlaf. I also have a fix for the #79 that you mentioned. 
When you have a moment, please take a look #279.

Thanks!

**Review by samlaf — APPROVED** [review]
Thanks a ton for this!

**Pull request merged**
